# Generated by Django 5.1.6 on 2026-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6),
        ),
    ]
